/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.HotelManagement;

import Model.Hotel.Amenities;
import Model.Hotel.Hotel;
import Model.Travel;
import static Utilities.Validations.validateName;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class AddAmenitiesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;

    /**
     * Creates new form AddAmenitiesJPanel
     */
    public AddAmenitiesJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtAmenitiesName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Amenities Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 100, 40));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 110, 40));

        txtAmenitiesName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtAmenitiesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 230, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel2.setText("Add Amenities");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:     
        String amenitiesName = txtAmenitiesName.getText();
        if(amenitiesName.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(validateName(amenitiesName)){
            JOptionPane.showMessageDialog(this, "Name should be between 3 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Amenities amenities = new Amenities();
        amenities.addFacility(amenitiesName);
        hotel.setAmenities(amenities);
        JOptionPane.showMessageDialog(this, "Amenity added successfuly!");
        txtAmenitiesName.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtAmenitiesName.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAmenitiesName;
    // End of variables declaration//GEN-END:variables
}
