/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.HotelManagement;

import Model.Hotel.Cuisine;
import Model.Hotel.Hotel;
import Model.Hotel.Room;
import Model.Travel;
import static Utilities.Validations.validateName;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class AddCuisinesJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;
    /**
     * Creates new form AddCuisinesJPanel
     */


    AddCuisinesJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel) {
initComponents();
            this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        optionsCuisineType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtDishName = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Cuisine Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        optionsCuisineType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsCuisineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Italian", "Chinese", "Indian", "Mexican", "Japanese" }));
        add(optionsCuisineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 230, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Dish Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        txtDishName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtDishName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, 50));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel3.setText("Add Cuisines");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String roomType = optionsCuisineType.getSelectedItem().toString();
        String dishName = txtDishName.getText();
        if(dishName.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(validateName(dishName)){
            JOptionPane.showMessageDialog(this, "Name should be between 3 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Cuisine cuisine = new Cuisine();
        Map<String,String> dish = new HashMap<>();
        dish.put(roomType, dishName);
        cuisine.setCuisine(dish);
        hotel.setCuisine(cuisine);
        JOptionPane.showMessageDialog(this, "Dish added successfuly in selected cuisine" );
        txtDishName.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtDishName.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> optionsCuisineType;
    private javax.swing.JTextField txtDishName;
    // End of variables declaration//GEN-END:variables
}
