/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.HotelManagement;

import Model.Hotel.Hotel;
import Model.Hotel.Room;
import Model.Organizations.Organization;
import Model.Travel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class AddRoomsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;
    ArrayList<Room> rooms = new ArrayList();

    /**
     * Creates new form AddRoomsJPanel
     */

    AddRoomsJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
        initComponents();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        optionsRoomType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtRoomNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Room Number:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Room Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        optionsRoomType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STANDARD", "DELUXE" }));
        add(optionsRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 230, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 230, 50));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 50));

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 90, 50));

        txtRoomNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 230, 50));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setText("Add Rooms");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String roomNo = txtRoomNo.getText();
        String roomType = optionsRoomType.getSelectedItem().toString();
        Double roomPrice = Double.parseDouble(txtPrice.getText());
                if(roomNo.isEmpty() || roomPrice.isNaN()){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Room room = new Room();
        room.setPrice(roomPrice);
        room.setRoomNumber(roomNo);
        room.setRoomType(roomType);
        rooms.add(room);
        hotel.setRooms(rooms);
        JOptionPane.showMessageDialog(this, "Room added successfuly!");
        txtPrice.setText("");
        txtRoomNo.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtPrice.setText("");
        txtRoomNo.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> optionsRoomType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNo;
    // End of variables declaration//GEN-END:variables
}
