/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.HotelManagement;

import Model.Hotel.Guest;
import Model.Hotel.Hotel;
import Model.Travel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samik
 */
public class ManageGuestsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;

    /**
     * Creates new form AddGuestsJPanel
     */

    ManageGuestsJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
        populateTable();
    }

        public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblGuests.getModel();
        dtm.setRowCount(0);
            if (hotel.getGuests() == null) {
        // Display a warning to the user
        JOptionPane.showMessageDialog(this, "No guests available in the hotel.", "Warning", JOptionPane.WARNING_MESSAGE);
        return; // Exit the method
    }
        for (Guest guest : hotel.getGuests()) {
            Object[] row = new Object[6];
            row[0] = guest;
            row[1] = guest.getCheckinDate();
            row[2] = guest.getCheckoutDate();
            row[3] = guest.getDurationOfStay();
            row[4] = guest.getRoomId();
            row[5] = guest.getSpecialRequests();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblGuests = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tblGuests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Checkin Date", "Checkout Date", "Duration Of Stay", "Room No", "Special Request"
            }
        ));
        jScrollPane2.setViewportView(tblGuests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGuests;
    // End of variables declaration//GEN-END:variables
}
