/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.EnterpriseAccessAdmin;

import Model.Travel;
import static Utilities.Validations.validatePassword;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author ASUS
 */
public class SetAccessEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SetAccessEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    private String role;
    
    public SetAccessEnterpriseJPanel(JPanel userProcessContainer, Travel travel, String role) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.role = role;
        lblUpdateHeader.setText("Update Admin Access for "+role);
        if(role == "Government Personnel"){
            txtUsername.setText(travel.getGovBoaAdmin().getUsername());
            txtPassword.setText(travel.getGovBoaAdmin().getPassword());
        }
        else if(role == "Transportation Board Personnel"){
            txtUsername.setText(travel.getTraBoaAdmin().getUsername());
            txtPassword.setText(travel.getTraBoaAdmin().getPassword());
        }
        else if(role == "Verification Authority"){
            txtUsername.setText(travel.getVerAuthAdmin().getUsername());
            txtPassword.setText(travel.getVerAuthAdmin().getPassword());
        }
        else if(role == "Financial Manager"){
            txtUsername.setText(travel.getFinManAdmin().getUsername());
            txtPassword.setText(travel.getFinManAdmin().getPassword());   
        }
        else{
            txtUsername.setText(travel.getHumResAdmin().getUsername());
            txtPassword.setText(travel.getHumResAdmin().getPassword());
        }
        txtPassword.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateHeader = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUpdatePassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdateHeader.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblUpdateHeader.setText("Update Admin Access");
        add(lblUpdateHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1120, 80));

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 103, 36));

        lblUpdatePassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUpdatePassword.setText("Password:");
        add(lblUpdatePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 103, 39));

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtUsername.setEnabled(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 40));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 210, 40));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, 40));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String inputPassword = new String(txtPassword.getPassword());
        if(inputPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please check if password field is filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(validatePassword(inputPassword)){
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String salt = BCrypt.gensalt();
        String cPassword = BCrypt.hashpw(inputPassword, salt);
        if(role == "Government Personnel")
            travel.getGovBoaAdmin().setPassword(cPassword);
        else if(role == "Transportation Board Personnel")
            travel.getTraBoaAdmin().setPassword(cPassword);
        else if(role == "Verification Authority")
            travel.getVerAuthAdmin().setPassword(cPassword);
        else if(role == "Financial Manager")
            travel.getFinManAdmin().setPassword(cPassword);
        else
            travel.getHumResAdmin().setPassword(cPassword);
        JOptionPane.showMessageDialog(this, "Password updated successfuly!");
        txtPassword.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         txtPassword.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblUpdateHeader;
    private javax.swing.JLabel lblUpdatePassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
