/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.OrganizationsManage;

import Model.Hotel.Hotel;
import Model.LocalBusiness.LocalBusiness;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import Model.TravelAgency.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class ViewOrganizationDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;
    private LocalBusiness localBusiness;
    private String type;
    private TransportAgency transportAgency;
    private TravelAgency travelAgency;

    /**
     * Creates new form ViewOrganizationDeatilsJPanel
     */
    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }

    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, LocalBusiness lb, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.localBusiness = lb;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }

    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, TransportAgency transportAgency, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.transportAgency = transportAgency;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }    
    
        ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, TravelAgency travelAgency, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.travelAgency = travelAgency;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtHq = new javax.swing.JTextField();
        lblHq = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        txtManagerEmail = new javax.swing.JTextField();
        lblManagerEmail = new javax.swing.JLabel();
        txtManagerContact = new javax.swing.JTextField();
        lblManagerContact = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        optionsType = new javax.swing.JComboBox<>();
        imgLogo = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        txtName.setEditable(false);

        lblDescription.setText("Description:");

        lblHq.setText("Location Headquarters:");

        lblName.setText("Organization Name:");

        lblManagerName.setText("Manager Name:");

        lblManagerEmail.setText("Manager Email:");

        lblManagerContact.setText("Manager Contact:");

        lblLogo.setText("Logo:");

        lblType.setText("Type:");

        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnUpdate)
                        .addGap(69, 69, 69)
                        .addComponent(btnSave)
                        .addGap(51, 51, 51)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblManagerEmail)
                            .addGap(24, 24, 24)
                            .addComponent(txtManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblManagerName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHq)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHq, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDescription))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblType)
                                .addComponent(lblManagerContact))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(txtManagerContact, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(optionsType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGap(119, 119, 119)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLogo)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblName)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogo)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(lblDescription)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHq)
                                .addComponent(txtHq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblManagerName)
                                .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblManagerEmail)
                                .addComponent(txtManagerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblManagerContact)
                                .addComponent(txtManagerContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblType)
                                .addComponent(optionsType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(90, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtDescription.setEditable(true);
        txtHq.setEditable(true);
        txtManagerContact.setEditable(true);
        txtManagerEmail.setEditable(true);
        txtManagerName.setEditable(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        if (type.equals("Hotel")) {
            hotel.setBusinessDescription(txtDescription.getText());
            hotel.setHeadquarter(txtHq.getText());
            hotel.setManagerEmail(txtManagerEmail.getText());
            hotel.setManagerName(txtManagerName.getText());
            hotel.setManagerPhone(txtManagerContact.getText());
        }
        if (type.equals("Local Business")) {
            localBusiness.setBusinessDescription(txtDescription.getText());
            localBusiness.setHeadquarter(txtHq.getText());
            localBusiness.setManagerEmail(txtManagerEmail.getText());
            localBusiness.setManagerName(txtManagerName.getText());
            localBusiness.setManagerPhone(txtManagerContact.getText());
        }
        if ((type.equals("Air"))|| (type.equals("Road")) || (type.equals("Rail")) || (type.equals("Sea"))) {
            transportAgency.setBusinessDescription(txtDescription.getText());
            transportAgency.setHeadquarter(txtHq.getText());
            transportAgency.setManagerEmail(txtManagerEmail.getText());
            transportAgency.setManagerName(txtManagerName.getText());
            transportAgency.setManagerPhone(txtManagerContact.getText());
        }   
                if (type.equals("Travel Agency")) {
            travelAgency.setBusinessDescription(txtDescription.getText());
            travelAgency.setHeadquarter(txtHq.getText());
            travelAgency.setManagerEmail(txtManagerEmail.getText());
            travelAgency.setManagerName(txtManagerName.getText());
            travelAgency.setManagerPhone(txtManagerContact.getText());
        }
        JOptionPane.showMessageDialog(this, "Organization Details updated successfuly!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if (component instanceof ViewOrganizationJPanel viewOrganizationJPanel) {
            viewOrganizationJPanel.populateTable();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateInformation() {
        if (type.equals("Hotel")) {
            txtDescription.setText(hotel.getBusinessDescription());
            txtHq.setText(hotel.getHeadquarter());
            txtManagerContact.setText(hotel.getManagerPhone());
            txtManagerEmail.setText(hotel.getManagerEmail());
            txtManagerName.setText(hotel.getManagerName());
            txtName.setText(hotel.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(hotel.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(hotel.getLogoImage());
        }
        if (type.equals("Local Business")) {
            txtDescription.setText(localBusiness.getBusinessDescription());
            txtHq.setText(localBusiness.getHeadquarter());
            txtManagerContact.setText(localBusiness.getManagerPhone());
            txtManagerEmail.setText(localBusiness.getManagerEmail());
            txtManagerName.setText(localBusiness.getManagerName());
            txtName.setText(localBusiness.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(localBusiness.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(localBusiness.getLogoImage());
        }
        if (type.equals("Local Business")) {
            txtDescription.setText(localBusiness.getBusinessDescription());
            txtHq.setText(localBusiness.getHeadquarter());
            txtManagerContact.setText(localBusiness.getManagerPhone());
            txtManagerEmail.setText(localBusiness.getManagerEmail());
            txtManagerName.setText(localBusiness.getManagerName());
            txtName.setText(localBusiness.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(localBusiness.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(localBusiness.getLogoImage());
        }  
        if ((type.equals("Air"))|| (type.equals("Road")) || (type.equals("Rail")) || (type.equals("Sea"))){
            txtDescription.setText(transportAgency.getBusinessDescription());
            txtHq.setText(transportAgency.getHeadquarter());
            txtManagerContact.setText(transportAgency.getManagerPhone());
            txtManagerEmail.setText(transportAgency.getManagerEmail());
            txtManagerName.setText(transportAgency.getManagerName());
            txtName.setText(transportAgency.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(transportAgency.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(transportAgency.getLogoImage());            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHq;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblManagerContact;
    private javax.swing.JLabel lblManagerEmail;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblType;
    private javax.swing.JComboBox<String> optionsType;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHq;
    private javax.swing.JTextField txtManagerContact;
    private javax.swing.JTextField txtManagerEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
