/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.TravelAgencyManagement;

import Model.TransportAgency.TransportAgency;
import Model.Travel;
import Model.TravelAgency.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class TravelAgencyManagementJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Travel travel;
   private TravelAgency travelAgency;
    private String username;
    /**
     * Creates new form TravelAgencyManagementJPanel
     */

    public TravelAgencyManagementJPanel(JPanel userProcessContainer, Travel travel, TravelAgency travelAgency, String usernameInput) {
        initComponents();
                this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.travelAgency = travelAgency;
        this.username = usernameInput;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManProfile = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        btnManStaff = new javax.swing.JButton();
        btnAddPlan = new javax.swing.JButton();
        btnManPlan = new javax.swing.JButton();

        btnManProfile.setText("Manage Profile");
        btnManProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManProfileActionPerformed(evt);
            }
        });

        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnManStaff.setText("Manage Staff");
        btnManStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManStaffActionPerformed(evt);
            }
        });

        btnAddPlan.setText("Add Plan");
        btnAddPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlanActionPerformed(evt);
            }
        });

        btnManPlan.setText("Manage Plan");
        btnManPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManProfile)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAddPlan))
                    .addComponent(btnAddStaff))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManStaff)
                    .addComponent(btnManPlan))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlan)
                    .addComponent(btnManPlan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManStaff)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddStaff)
                        .addGap(54, 54, 54)))
                .addComponent(btnManProfile)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManProfileActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel panel = new ManageProfileJPanel(userProcessContainer, travel, travelAgency, username);
        userProcessContainer.add("ManageProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManProfileActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        AddStaffJPanel panel = new AddStaffJPanel(userProcessContainer, travel, travelAgency);
        userProcessContainer.add("AddStaffJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnManStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManStaffActionPerformed
        // TODO add your handling code here:
        ManageStaffPanel panel = new ManageStaffPanel(userProcessContainer, travel, travelAgency);
        userProcessContainer.add("ManageStaffPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManStaffActionPerformed

    private void btnAddPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlanActionPerformed
        // TODO add your handling code here:
        AddPlanJPanel panel = new AddPlanJPanel(userProcessContainer, travel, travelAgency);
        userProcessContainer.add("AddPlanJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_btnAddPlanActionPerformed

    private void btnManPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManPlanActionPerformed
        // TODO add your handling code here:
        ManagePlanJPanel panel = new ManagePlanJPanel(userProcessContainer, travel, travelAgency);
        userProcessContainer.add("ManagePlanJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnManPlanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlan;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnManPlan;
    private javax.swing.JButton btnManProfile;
    private javax.swing.JButton btnManStaff;
    // End of variables declaration//GEN-END:variables
}
