/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Register;

import Model.Roles.Customer;
import Model.Travel;
import UI.WorkAreas.Customer.CustomerJPanel;
import UI.WorkAreas.Login.NewPasswordJPanel;
import static Utilities.SendEmail.generateVerificationCode;
import static Utilities.SendEmail.sendVerificationCode;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.Random;
import javax.swing.JPanel;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;

/**
 *
 * @author samik
 */
public class VerificationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    String email;
    int verificationCode;
    String username;
    boolean isForgotPassword;

    /**
     * Creates new form VerificationJPanel
     */

    public VerificationJPanel(JPanel userProcessContainer, Travel travel, String email, String username, int verificationCode, boolean isForgotPassword) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.email = email;
        this.verificationCode = verificationCode;
        this.username = username;
        this.isForgotPassword = isForgotPassword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnResend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Verify Your Account");

        jLabel2.setText("We email you the six digit code to registered email");

        jLabel3.setText("Enter the code below to confirm your email address");

        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        jLabel4.setText("If you didn't receive the code");

        btnResend.setText("Resend");
        btnResend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResendActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerify)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnResend)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVerify)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnResend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendActionPerformed
        // TODO add your handling code here:
        txtInput.setText("");
        verificationCode = generateVerificationCode();
        boolean emailSent;
        if (isForgotPassword) {
            emailSent = sendVerificationCode(email, username, verificationCode, true);
        } else {
            emailSent = sendVerificationCode(email, username, verificationCode, false);
        }
        if (emailSent) {
            JOptionPane.showMessageDialog(null, "Verfication Code sent to " + email);
        } else {
            JOptionPane.showMessageDialog(null, "Failed to send the verification code to the email. Please Retry again.");
        }
    }//GEN-LAST:event_btnResendActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:

        int enteredCode = Integer.parseInt(txtInput.getText());
        Customer customer = travel.getCustomerDirectory().searchCustomerByEmail(email);
        // Verify the entered code
        if (enteredCode == verificationCode) {
            if (!isForgotPassword) {
                // Registration successful
                System.out.println("Registration successful! Welcome, " + email + "!");

                customer.setStatus("Verfied");
                CustomerJPanel panel = new CustomerJPanel(userProcessContainer, travel, customer);
                userProcessContainer.add("CustomerJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                return;
            } else {
                NewPasswordJPanel panel = new NewPasswordJPanel(userProcessContainer, travel, customer);
                userProcessContainer.add("NewPasswordJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                return;
            }
        } else {
            // Registration failed
            JOptionPane.showMessageDialog(this, "Verification code incorrect. Registration failed.", "Credentials Error", JOptionPane.ERROR_MESSAGE);
        }
        txtInput.setText("");

    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResend;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
