/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Customer;

import Model.Roles.Customer;
import Model.Travel;
import UI.WorkAreas.HotelManagement.ManageRoomsJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
/**
 *
 * @author ASUS
 */
public class CustomerAddCurrencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAddCurrencyJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    Customer customer;
    DecimalFormat decimalFormat = new DecimalFormat("#.##");
    String currencyType;
    
    public CustomerAddCurrencyJPanel(JPanel userProcessContainer, Travel travel, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.customer = customer;
        btnReceipt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrencyType = new javax.swing.JLabel();
        txtAmountAdd = new javax.swing.JTextField();
        btnAddAmount = new javax.swing.JButton();
        lblAddBalance = new javax.swing.JLabel();
        optionsCurrencyType = new javax.swing.JComboBox<>();
        lblAmountAdd = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();

        lblCurrencyType.setText("Currency type:");

        btnAddAmount.setText("Add Amount");
        btnAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAmountActionPerformed(evt);
            }
        });

        lblAddBalance.setText("Add Balance:");

        optionsCurrencyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNY", "EUR", "INR", "USD" }));

        lblAmountAdd.setText("Amount:");

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        btnReceipt.setText("Download Receipt ");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtAmountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAddAmount)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblCurrencyType)
                                                .addComponent(lblAmountAdd))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(optionsCurrencyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblAddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblAddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmountAdd)
                    .addComponent(txtAmountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrencyType)
                    .addComponent(optionsCurrencyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAmount)
                    .addComponent(btnReceipt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(btnBack2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if(component instanceof CustomerCurrencyJPanel customerCurrencyJPanel) {
            customerCurrencyJPanel.updateCurrency();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAmountActionPerformed
        // TODO add your handling code here:
        if(txtAmountAdd.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Double.valueOf(txtAmountAdd.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Value should be Integer!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         currencyType = (String) optionsCurrencyType.getSelectedItem();
        customer.getCurrency().put(currencyType, Double.valueOf(txtAmountAdd.getText()));
        JOptionPane.showMessageDialog(this, "Amount added successfuly!");
        txtAmountAdd.setText("");
        btnReceipt.setEnabled(true);
    }//GEN-LAST:event_btnAddAmountActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        // TODO add your handling code here:
        String path = "";
        JFileChooser jFile = new JFileChooser();
        jFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = jFile.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = jFile.getSelectedFile().getPath();
        }
        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "/topupamount.pdf"));
            doc.open();
            Paragraph title = new Paragraph("TOP UP AMOUNT BILLING");
            title.setSpacingBefore(20f);
            title.setSpacingAfter(20f);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            Paragraph name = new Paragraph("Customer Name: " + customer.getName());
            doc.add(name);
            Paragraph nameId = new Paragraph("Customer Email: " + customer.getEmail());
            doc.add(nameId);
            Paragraph nameC = new Paragraph("Customer Contact: " + customer.getPhone());
            doc.add(nameC);

            PdfPTable tblCertificate = new PdfPTable(2);
            tblCertificate.addCell("Top Up Amount");
            tblCertificate.addCell("Status");
            tblCertificate.addCell(txtAmountAdd.getText());
            tblCertificate.addCell("Successful");
            doc.add(tblCertificate);
            Paragraph concern = new Paragraph("If you have any questions or concerns, feel free to reach out to us .");
            concern.setSpacingBefore(100f);
            doc.add(concern);
            Paragraph email = new Paragraph("Email: stravelswift@gmail.com");
            email.setSpacingAfter(20f);
            doc.add(email);
            Paragraph electronicStatement = new Paragraph("This is an electronically generated document and doesn't require any signature or external verification.");
            electronicStatement.setSpacingBefore(50f);
            doc.add(electronicStatement);
            doc.close();
            JOptionPane.showMessageDialog(null, "Downloaded PDF File", "ALERT_MESSAGE", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CustomerConvertCurrenyJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(CustomerConvertCurrenyJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAmount;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JLabel lblAddBalance;
    private javax.swing.JLabel lblAmountAdd;
    private javax.swing.JLabel lblCurrencyType;
    private javax.swing.JComboBox<String> optionsCurrencyType;
    private javax.swing.JTextField txtAmountAdd;
    // End of variables declaration//GEN-END:variables
}
