/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Customer;

import Model.Roles.Customer;
import Model.Travel;
import UI.WorkAreas.VerificationBoard.VerificationBoardMainJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class CustomerJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Travel travel;
    Customer customer;
  
    /**
     * Creates new form CustomerJPanel
     */

    public CustomerJPanel(JPanel userProcessContainer, Travel travel, Customer customer) {
        initComponents();    
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
       this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnBookTrip = new javax.swing.JButton();
        btnViewCBooking = new javax.swing.JButton();
        btnBookLocal = new javax.swing.JButton();
        btnCurrency = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnViewLocal = new javax.swing.JButton();
        btnApplyCarrer = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        lblWelcome.setText("Hi Customer");

        btnBookTrip.setText("Book a Trip");
        btnBookTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTripActionPerformed(evt);
            }
        });

        btnViewCBooking.setText("View Current Booking");
        btnViewCBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCBookingActionPerformed(evt);
            }
        });

        btnBookLocal.setText("Book a Local Business Activity");
        btnBookLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookLocalActionPerformed(evt);
            }
        });

        btnCurrency.setText("Currency Management");
        btnCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrencyActionPerformed(evt);
            }
        });

        btnManageProfile.setText("Manage Profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnViewLocal.setText("View Local Business Activity Booking");
        btnViewLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalActionPerformed(evt);
            }
        });

        btnApplyCarrer.setText("Apply For Career");
        btnApplyCarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyCarrerActionPerformed(evt);
            }
        });

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBookLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookTrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApplyCarrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(538, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(67, 67, 67)
                .addComponent(btnBookTrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurrency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApplyCarrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(btnBack2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        CustomerProfileJPanel panel = new CustomerProfileJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrencyActionPerformed
        // TODO add your handling code here:
        CustomerCurrencyJPanel panel = new CustomerCurrencyJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerCurrencyJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrencyActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnApplyCarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyCarrerActionPerformed
        // TODO add your handling code here:
        CustomerCareerJPanel panel = new CustomerCareerJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerCareerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnApplyCarrerActionPerformed

    private void btnViewLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalActionPerformed
        // TODO add your handling code here:
        CustomerViewLocalBusinessJPanel panel = new CustomerViewLocalBusinessJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerViewLocalBusinessJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewLocalActionPerformed

    private void btnBookLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookLocalActionPerformed
        // TODO add your handling code here:
        CustomerAddBookingLocalBusinessJPanel panel = new CustomerAddBookingLocalBusinessJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerAddBookingLocalBusinessJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBookLocalActionPerformed

    private void btnBookTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTripActionPerformed
        // TODO add your handling code here:
        CustomerBookTripJPanel panel = new CustomerBookTripJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerBookTripJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBookTripActionPerformed

    private void btnViewCBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCBookingActionPerformed
        // TODO add your handling code here:
        CustomerViewBookTripJPanel panel = new CustomerViewBookTripJPanel(userProcessContainer, travel, customer);
        userProcessContainer.add("CustomerViewBookTripJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewCBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyCarrer;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBookLocal;
    private javax.swing.JButton btnBookTrip;
    private javax.swing.JButton btnCurrency;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnViewCBooking;
    private javax.swing.JButton btnViewLocal;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
