/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Login;

import Model.Directories.TravelAgencyDirectory;
import Model.Hotel.Hotel;
import Model.LocalBusiness.LocalBusiness;
import Model.Travel;
import Model.TransportAgency.TransportAgency;
import Model.TravelAgency.TravelAgency;
import UI.WorkAreas.Analytics.GraphJPanel;
import UI.WorkAreas.ApplicationAdmin.ApplicationAdminMainJPanel;
import UI.WorkAreas.CarrerBoard.CarrerBoardMainJPanel;
import UI.WorkAreas.FinancialBoard.FinancialBoardMainJPanel;
import UI.WorkAreas.GovernmentBoard.GovernmentBoardMainJPanel;
import UI.WorkAreas.HotelManagement.HotelManagementJPanel;
import UI.WorkAreas.LocalBusinessManagement.LocalBusinessManagementJPanel;
import UI.WorkAreas.TransportAgencyManagement.TransportAgencyManagementJPanel;
import UI.WorkAreas.TransportationBoard.TransportationBoardMainJPanel;
import UI.WorkAreas.TravelAgencyManagement.TravelAgencyManagementJPanel;
import UI.WorkAreas.VerificationBoard.VerificationBoardMainJPanel;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author ASUS
 */
public class AdminLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;

    public AdminLoginJPanel(JPanel userProcessContainer, Travel travel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblLogin.setText("Login");
        add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 135, 90));

        txtUserName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 147, 210, 40));

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 120, 22));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 120, -1));

        btnLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 80, -1));

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 80, -1));

<<<<<<< Updated upstream
        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 217, 210, 40));
=======
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogin)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(238, 238, 238)))
                .addComponent(btnBack)
                .addGap(15, 15, 15))
        );
>>>>>>> Stashed changes
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String usernameInput = txtUserName.getText().trim();
        String passwordInput = String.valueOf(txtPassword.getPassword());
        if (usernameInput.isEmpty() || passwordInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ((usernameInput.equals(travel.getAppAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getAppAdmin().getPassword()))) {
            ApplicationAdminMainJPanel panel = new ApplicationAdminMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("ApplicationAdminMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        if ((usernameInput.equals(travel.getGovBoaAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getGovBoaAdmin().getPassword()))) {
            GovernmentBoardMainJPanel panel = new GovernmentBoardMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("GovernmentBoardMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        if ((usernameInput.equals(travel.getTraBoaAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getTraBoaAdmin().getPassword()))) {
            TransportationBoardMainJPanel panel = new TransportationBoardMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("TransportationBoardMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        if ((usernameInput.equals(travel.getVerAuthAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getVerAuthAdmin().getPassword()))) {
            VerificationBoardMainJPanel panel = new VerificationBoardMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("VerificationBoardMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        if ((usernameInput.equals(travel.getFinManAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getFinManAdmin().getPassword()))) {
            FinancialBoardMainJPanel panel = new FinancialBoardMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("FinancialBoardMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        if ((usernameInput.equals(travel.getHumResAdmin().getUsername())) && (BCrypt.checkpw(passwordInput, travel.getHumResAdmin().getPassword()))) {
            CarrerBoardMainJPanel panel = new CarrerBoardMainJPanel(userProcessContainer, travel);
            userProcessContainer.add("CarrerBoardMainJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtPassword.setText("");
            return;
        }
        
        for (Hotel hotel : travel.getHotelDirectory().getHotelList()) {
            for (Map.Entry<String, String> entry : hotel.getLoginCredentials().entrySet()) {
                if (usernameInput.equals(entry.getKey()) && (passwordInput.equals(entry.getValue()))) {
                    HotelManagementJPanel panel = new HotelManagementJPanel(userProcessContainer, travel, hotel, usernameInput);
                    userProcessContainer.add("HotelManagementJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    return;
                }
            }
        }

        for (LocalBusiness localBusiness : travel.getLocalBusinessDirectory().getLocalBusinessList()) {
            for (Map.Entry<String, String> entry : localBusiness.getLoginCredentials().entrySet()) {
                if (usernameInput.equals(entry.getKey()) && (passwordInput.equals(entry.getValue()))) {
                    LocalBusinessManagementJPanel panel = new LocalBusinessManagementJPanel(userProcessContainer, travel, localBusiness, usernameInput);
                    userProcessContainer.add("LocalBusinessManagementJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    return;
                }
            }
        }

        for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
            for (Map.Entry<String, String> entry : transportAgency.getLoginCredentials().entrySet()) {
                if (usernameInput.equals(entry.getKey()) && (passwordInput.equals(entry.getValue()))) {
                    TransportAgencyManagementJPanel panel = new TransportAgencyManagementJPanel(userProcessContainer, travel, transportAgency, usernameInput);
                    userProcessContainer.add("TransportAgencyManagementJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    return;
                }
            }
        }        

        for (TravelAgency travelAgency : travel.getTravelAgencyDirectory().getTravelAgencyList()) {
            for (Map.Entry<String, String> entry : travelAgency.getLoginCredentials().entrySet()) {
                if (usernameInput.equals(entry.getKey()) && (passwordInput.equals(entry.getValue()))) {
                    TravelAgencyManagementJPanel panel = new TravelAgencyManagementJPanel(userProcessContainer, travel, travelAgency, usernameInput);
                    userProcessContainer.add("TravelAgencyManagementJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    return;
                }
            }
        }         
        
        JOptionPane.showMessageDialog(this, "Incorrect Username or Password.", "Credentials Error", JOptionPane.ERROR_MESSAGE);
        txtPassword.setText("");

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                            GraphJPanel panel = new GraphJPanel();
            userProcessContainer.add("GraphJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
