/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Login;

import Model.Roles.Customer;
import Model.Travel;
import UI.WorkAreas.Customer.CustomerJPanel;
import UI.WorkAreas.Register.VerificationJPanel;
import static Utilities.SendEmail.generateVerificationCode;
import static Utilities.SendEmail.sendVerificationCode;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class ForgotPasswordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPasswordJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    String username;

    ForgotPasswordJPanel(JPanel userProcessContainer, Travel travel, String username) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel1.setText("Recover Your Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 300, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Enter Registered Email: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();

        for (Customer customer : travel.getCustomerDirectory().getCustomerList()) {
            if (customer.getEmail().equals(email)) {
                int verificationCode = generateVerificationCode();
                boolean emailSent = sendVerificationCode(email, username, verificationCode, true);
                JOptionPane.showMessageDialog(null, "Verfication Code sent to " + email);
                if (emailSent) {
                    VerificationJPanel panel = new VerificationJPanel(userProcessContainer, travel, email, customer.getUsername(), verificationCode, true);
                    userProcessContainer.add("VerificationJPanel", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    return;
                } else {
                    // Email sending failed
                    JOptionPane.showMessageDialog(null, "Failed to send the verification code to the email. Please Retry again.");
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Entered email is not registered.", "Credentials Error", JOptionPane.ERROR_MESSAGE);
        txtEmail.setText("");

    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
