/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.LocalBusinessManagement;

import Model.LocalBusiness.LocalActivity;
import Model.Travel;
import static Utilities.Validations.validateName;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samik
 */
public class ViewLocalActivityDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLocalActivityDetailsJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    private LocalActivity localActivity;

    ViewLocalActivityDetailsJPanel(JPanel userProcessContainer, Travel travel, LocalActivity localActivity) {
 initComponents();
                 this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.localActivity = localActivity;
                btnSave.setEnabled(false);
        populateInfo();
    }

        private void populateInfo(){
        txtType.setText(localActivity.getType());
        txtLoc.setText(localActivity.getLocation());
        txtDesc.setText(localActivity.getDescription());
        txtCost.setText(String.valueOf(localActivity.getCost()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCost = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCost.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 250, 40));

        txtLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 250, 40));

        txtDesc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 177, 250, 40));

        txtType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 250, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Cost:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Local Activity Description:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Local Activity Type: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 210, 30));

        btnBack2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, 90, 40));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, 40));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel5.setText("View Local Activity Details");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if(component instanceof ManageLocalActivityJPanel manageLocalActivityJPanel) {
            manageLocalActivityJPanel.populateTable();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        String type = txtType.getText();
        String description = txtDesc.getText();
        String location = txtLoc.getText();
        int cost = Integer.parseInt(txtCost.getText());
        if(type.isEmpty() || description.isEmpty() || location.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
                if(validateName(type)){
            JOptionPane.showMessageDialog(this, "Type should be between 3 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
                                if(validateName(description)){
            JOptionPane.showMessageDialog(this, "Type should be between 3 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
                                if(validateName(location)){
            JOptionPane.showMessageDialog(this, "Type should be between 3 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }   
                              
        localActivity.setCost(cost);
        localActivity.setDescription(description);
        localActivity.setLocation(location);
        localActivity.setType(type);

        JOptionPane.showMessageDialog(this, "Local Activity Details updated successfuly!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
